CREATE DATABASE DB_BARBEARIA;
USE DB_BARBEARIA;

CREATE TABLE TB_ADMIN(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(200) NOT NULL,
    SENHA VARCHAR(200) NOT NULL
);

CREATE TABLE TB_FUNCIONARIO(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    FUNCIONARIO VARCHAR(200)
);

CREATE TABLE TB_CORTE(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CORTE VARCHAR(200),
    PRECO FLOAT
);



CREATE TABLE TB_CORTES_EFECTUADOS(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    IDFUNCIONARIO INT NOT NULL,
    IDCORTE INT NOT NULL,
    FOREIGN KEY(IDFUNCIONARIO)
    REFERENCES TB_FUNCIONARIO(ID),
    FOREIGN KEY (IDCORTE)
    REFERENCES TB_CORTE(ID)
);


/*SELECIONAR CORTES EFECTUADOS O FUNCIONARIO O CORTE E O PREÇO*/

SELECT  F.FUNCIONARIO, C.CORTE, C.PRECO
FROM TB_CORTES_EFECTUADOS E 
INNER JOIN TB_FUNCIONARIO  F 
ON E.IDFUNCIONARIO = F.ID
INNER JOIN TB_CORTE C
ON E.IDCORTE = C.ID ;

/* SOMA DO LUCRO TOTAL */

SELECT SUM(C.PRECO) 
FROM TB_CORTES_EFECTUADOS E 
INNER JOIN TB_CORTE C
ON E.IDCORTE = C.ID;

/* SOMA DO LUCRO FUNCIONARIO */
SELECT SUM(C.PRECO) AS 'TOTAL', F.FUNCIONARIO 
FROM TB_CORTES_EFECTUADOS E 
INNER JOIN TB_CORTE C
ON E.IDCORTE = C.ID 
INNER JOIN TB_FUNCIONARIO F 
ON E.IDFUNCIONARIO = F.ID WHERE F.FUNCIONARIO = "JOSE";





/*ALGUNS DADOS PARA TESTAR */

/*INSERIR CLIENTE*/
INSERT INTO TB_FUNCIONARIO (FUNCIONARIO) VALUES ("ANDRE");
INSERT INTO TB_FUNCIONARIO (FUNCIONARIO) VALUES ("JOSE");
INSERT INTO TB_FUNCIONARIO (FUNCIONARIO) VALUES ("LUIS");
INSERT INTO TB_FUNCIONARIO (FUNCIONARIO) VALUES ("PAULO");

/*INSERIR CORTES*/
INSERT INTO TB_CORTE (CORTE, PRECO)
VALUES("TRANÇAS - VIRADAS", 2000),
("FREESTYLE - CACHEADO", 1400),
("DOIS TEMPOS - CLÁSSICO", 800),
("DOIS TEMPOS - CACHEADO", 1500),
("FREESTYLE - BRANCO", 1000),
("TRANÇAS - AMERICANAS", 1800),
("PINTURA - RUIVO", 1000),
("PINTURA - LOIRO", 800),
("PINTURA - PLATINADO", 1200),
("PINTURA - ROSA", 1500),
("PINTURA - ROXO", 1800),
("DOIS TEMPOS - RISCO", 1200),
("FREESTYLE CLÁSSICO", 800);

/*INSERIR CORTES EFECTUADOS*/

INSERT INTO TB_CORTES_EFECTUADOS
(IDFUNCIONARIO, IDCORTE)
VALUES(1, 2);

INSERT INTO TB_CORTES_EFECTUADOS
(IDFUNCIONARIO, IDCORTE)
VALUES(2, 3);

INSERT INTO TB_CORTES_EFECTUADOS
(IDFUNCIONARIO, IDCORTE)
VALUES(2, 1);
